---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http
spec:
  parentRefs:
  - name: gateway
    namespace: one
  hostnames: ["dual.example.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /two
    backendRefs:
    - name: foo
      port: 8080
