apiVersion: kustomize.config.k8s.io/v1beta1
namespace: one
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- patch-gateway.yaml
patches:
- patch: |-
    - op: replace
      path: "/spec/hostnames/0"
      value: "dual.example.com"
  target:
    group: gateway.networking.k8s.io
    version: v1alpha2
    kind: HTTPRoute
- path: patch-gateway.yaml
